//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace DAL.DAO
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class alquiler
//    {
//        public int ID_ALQUILER { get; set; }
//        public Nullable<int> ID_CLIENTE { get; set; }
//        public Nullable<int> ID_DETALLE_ALQUILER { get; set; }
//        public string OBSERVACIONES { get; set; }
    
//        public virtual cliente Cliente { get; set; }
//        public virtual dalquiler DAlquiler { get; set; }
//    }
//}
