//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace DAL.DAO
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class cliente
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public cliente()
//        {
//            this.Alquiler = new HashSet<alquiler>();
//        }
    
//        public int ID_CLIENTE { get; set; }
//        public string NOMBRE_CLIENTE { get; set; }
//        public string APELLIDO_CLIENTE { get; set; }
//        public string CORREO_CLIENTE { get; set; }
    
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<alquiler> Alquiler { get; set; }
//    }
//}
