//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace DAL.DAO
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class dalquiler
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public dalquiler()
//        {
//            this.Alquiler = new HashSet<alquiler>();
//        }
    
//        public int ID_DETALLE_ALQUILER { get; set; }
//        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
//        public Nullable<System.DateTime> FECHA_FIN { get; set; }
//        public string ESTADO { get; set; }
//        public Nullable<int> ID_PAGO { get; set; }
//        public Nullable<int> ID_LIBRO { get; set; }
    
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<alquiler> Alquiler { get; set; }
//        public virtual libro Libro { get; set; }
//        public virtual pago Pago { get; set; }
//    }
}
