//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace DAL.DAO
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class editorial
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public editorial()
//        {
//            this.Libro = new HashSet<libro>();
//        }
    
//        public int ID_EDITORIAL { get; set; }
//        public string NOMBRE_EDITORIAL { get; set; }
//        public Nullable<int> TELEFONO { get; set; }
//        public string DIRECCION { get; set; }
//        public string PAIS { get; set; }
    
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<libro> Libro { get; set; }
//    }
//}
