//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace DAL.DAO
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class usuario
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public usuario()
//        {
//            this.UsuarioPermiso = new HashSet<usuarioPermiso>();
//        }
    
//        public int ID_USUARIO { get; set; }
//        public string USUARIO1 { get; set; }
//        public string CONTRA { get; set; }
    
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<usuarioPermiso> UsuarioPermiso { get; set; }
//    }
//}
